language: node_js
sudo: false
node_js:
  - stable
  - '0.12'
env:
  global:
    - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
    - LOGS_DIR=/tmp/reac-context-hoc-build/logs
    - USE_CLOUD=false
    - secure: esVGgNUvmaLDc3TLryoqK8I6rc1IxAkdnQ8ZoWzKRM7bTnAMioI+L9HgWDgGsdeAsI0JZddVbsWnbSqUJ69pzqMVC5lBIBlgRrKiFy6HRe2YHoRaoKihkGLN0lV+4hM4lvmP52RsMdgjU+hcCxI8u9fQQMKYuDAvELu0+44w6ff/lDWBoxYI2o5Ct2Npcxhz8xQt4PvAjEZ5B2cHTE7pHuwgn71gqiOCr0YvHE3RXnZBOsgTF9qwi8ZnNo8xLbcd8zQtJyo5MTqSfLT8rSSVV/B9zSrMRkXtf+d4SxofLkq6E2gVwIw58x4tUN81qV+Dw4cPGTyjevBvDpAOWfgg61kYmAMS8fMIGfnDJk2DJKiRpIkwCe1pHnsGGkyr7R/P0xqGJdopoElOtq24LkKowSXCW+VJaipXkh6sqtBESCjkGChw78f4E4fb/wtVMDt3+SrWOp8TtiYcrFOxucEhs5n01ZM4QJLGNvdSFwbO9t2QFqauXFDhhp1rZusZf7//WWUSqE9zbfwFFiqnYWD8AzI2kXTpfigRuSxh/BF4z2TWEbtlgOLB4RQNhRoZYnTqBZ8YiUhzCuZ65U3FnfUDWveOITmi6oOmvavlVYbYF2y+ZiJlTRNepry3moaT4uDSBuXcYCsY7i6GZbCmMfrxCWoFarzD5zY43q4pm+gVUfQ=
    - secure: aygDLwiyUfV5q8dzYcCOnmzRFK3UATnfQHLtQwzn6GMR9AoRGkFyy45Eo/iOCMTP+Zs5WGcaaZxZjGa4fLQJZz52GSu4WUyEG4gJqd7AHD416BofWeXYGWqIBT9pxh4HOfqR4SI7PZ8TYYYNPu+rrcr+q8w8xWAeyXQTc7Fewup3zY9wb9gxF+SDzHZ+1vwtFT+Bbwt65bYExlcbfZbv197KL4eXzPkhr1294UCs/kHPTBgypvJrezCxwwSnwgdNoIs7r6FpUHQ9ZvZ5c4braxus83LJnNLpI538v9XjZy2PPEITljg0wq96+ZjwavYwsrbXCo9r6eJCmtLS4bs09J4MyM0H+KGi30aWFyWllGNAkaEzabQL8aYoVcEOBg1I0HYcsr8OEViPr9mfaMTx78p4dd03j4u5JLxtGk1emrk9klJtk8YkLfdjrXUHFy4rsbMZePMVqmMnSAkpSwovDg9bYef+KrjSFGtTnHCqx995CotOYa0n+w0T4f4okaGlNSnhD81zZ8DPGyWPV41QkpWE9crYs1eX74IdZrgH2VI6xu/XFIQ1v0NQckNO7NSjlbCZ+ngICOd4qxoVvkr+3+g/UlK0w8HzFHrbuD1gS7QDz7SrTJRGsa0TemafWbDcr4MMC9s4Yr33S1ZZio7hAYa34Brj7+j/741Wer/Yr3M=
matrix:
  include:
    - node_js: stable
      env: USE_CLOUD=true
  allow_failures:
    - env: USE_CLOUD=true
#addons:
  #sauce_connect: true
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - mkdir -p $LOGS_DIR
  - ./scripts/setup.sh
script:
  - npm test
after_script:
- ./scripts/teardown.sh
