language: node_js
sudo: false
node_js:
  - stable
  - '0.12'
env:
  global:
    - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
    - LOGS_DIR=/tmp/reac-context-hoc-build/logs
    - USE_CLOUD=false
    #- SAUCE_USERNAME=react-context-hoc2
    #- SAUCE_ACCESS_KEY=edf3e80aa98e-676b-6dd4-ee81-06deda90
matrix:
  fast_finish: true
  include:
    - node_js: stable
      env: USE_CLOUD=true
  allow_failures:
    - env: USE_CLOUD=true
#addons:
  #sauce_connect: true
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  #- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] && SAUCE_USERNAME="react-context-hoc" && SAUCE_ACCESS_KEY="b9a0e405dfee-bb18-3554-c4f6-895c61ae" || true'
before_script:
  - mkdir -p $LOGS_DIR
  - ./scripts/setup.sh
script:
  - npm test
after_script:
  - ./scripts/teardown.sh
