language: node_js
sudo: false
node_js:
  - stable
  - '0.12'
env:
  global:
    #- BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
    #- LOGS_DIR=/tmp/reac-context-hoc-build/logs
    - USE_CLOUD=false
    - SAUCE_USERNAME=react-context-hoc
    - SAUCE_ACCESS_KEY=b9a0e405dfee-bb18-3554-c4f6-895c61ae
matrix:
  fast_finish: true
  include:
    - node_js: stable
      env: USE_CLOUD=true
  allow_failures:
    - env: USE_CLOUD=true
addons:
  sauce_connect: true
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
#before_script:
  #- mkdir -p $LOGS_DIR
  #- ./scripts/setup.sh
script:
  - npm test
#after_script:
  #- ./scripts/teardown.sh
